import networkx
import pandas as pd
import geopandas as gp


def get_list_of_data(filepath, col_name):
    '''Pull a column data from a shape or CSV file.

    :param filepath: The path to where your data is located.

    :param col_name: A list of the columns of data you want to grab.
    :return: A list of the data you have specified.

    '''
    # Checks if you have inputed a csv or shp file then captures the data
    data = []
    if filepath.split('.')[-1] == 'csv':
        df = pd.read_csv(filepath)
        for i in col_name:
            data.append(df[i])
        return data
    if filepath.split('.')[-1] == 'shp':
        df = gp.read_file(filepath)
        for i in col_name:
            data.append(df[i])
        return data


def add_data_to_graph(data, graph, data_name):
    '''Add a list of data to graph nodes.

    :data: A column with the data you would like to add to the nodes(VTDs).
    :graph: The graph you constructed and want to run chain on.

    :data_name: A list of the attribute names you are adding.

    '''
    # Check to make sure there is a one-to-one between data and VTDs
    for i, j in enumerate(data_name):
        if len(graph) != len(data[i]):
            raise ValueError("Your column length doesn't match the number of nodes!")

    # Adding data to the nodes
        for x, _ in enumerate(graph.nodes()):
            graph.nodes[x][j] = data[i][x]


def construct_graph(vtds):
    '''Construct initial graph from information about neighboring VTDs.

    :vtds: A dict of dict of dicts generated by :func:`.ingest`.
    :returns: Networkx Graph.

    '''

    graph = networkx.from_dict_of_dicts(vtds)
    graph = networkx.convert_node_labels_to_integers(
        graph, label_attribute='old_id')

    return graph


def pull_districts(graph, cd_identifier):
    '''Creates dictionary of nodes to their CD.

    :param graph: The graph object you are working on.
    :param cd_identifier: How the congressional district is labeled on your graph.
    :return: A dictionary.
    '''
    # creates a dictionary and iterates over the nodes to add node to CD.
    nodes = {}
    for (p, d) in graph.nodes(data=True):
        nodes[p] = d[cd_identifier]
    return nodes
